name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - name: Install GDAL
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdal-dev gdal-bin
      - name: Install GDAL
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdal-dev gdal-bin
      - run: |
          rustup update ${{ matrix.toolchain }} && \
          rustup default ${{ matrix.toolchain }} && \
          cargo build --verbose && \
          cargo test --verbose
